services:
  - type: web
    name: lms-frontend
    env: static
    staticPublishPath: frontend/dist
    buildCommand: yarn install && yarn build
    pullRequestPreviewsEnabled: true

  - type: web
    name: lms-backend
    env: docker
    dockerfilePath: ./docker/Dockerfile
    startCommand: bench start
    envVars:
      - key: SITE_NAME
        value: site.localhost
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: REDIS_CACHE
        value: redis://redis-cache:6379
      - key: REDIS_QUEUE
        value: redis://redis-queue:6379
      - key: REDIS_SOCKETIO
        value: redis://redis-socketio:6379

  - type: redis
    name: redis-cache

  - type: redis
    name: redis-queue

  - type: redis
    name: redis-socketio

  - type: pserv
    name: mariadb
    env: docker
    dockerfilePath: ./docker/mariadb.Dockerfile
